In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("../CSV Files/backery.csv")

In [4]:
df.head()

,OrderID,Date,Time,Customer,Category,Product,Quantity,UnitPrice,PaymentMethod
0,1001,2026-06-01,08:15,Alice,Bread,Sourdough Loaf,2,5.50,Card
1,1002,2026-06-01,08:32,Bob,Pastry,Croissant,4,2.75,Cash
2,1003,2026-06-01,09:10,Charlie,Cake,Chocolate Cake Slice,2,4.50,UPI
3,1004,2026-06-01,09:45,Diana,Coffee,Cappuccino,1,3.50,Card
4,1005,2026-06-01,10:05,Ethan,Cookie,Chocolate Chip Cookie,6,1.50,Cash

In [5]:
df.tail()

,OrderID,Date,Time,Customer,Category,Product,Quantity,UnitPrice,PaymentMethod
15,1016,2026-06-02,10:55,Paula,Coffee,Mocha,1,4.50,Card
16,1017,2026-06-02,11:30,Quinn,Bread,Rye Bread,2,5.20,Cash
17,1018,2026-06-02,12:05,Rachel,Pastry,Pain au Chocolat,4,3.75,Card
18,1019,2026-06-02,12:40,Sam,Cake,Carrot Cake Slice,2,4.75,UPI
19,1020,2026-06-02,13:10,Tina,Coffee,Flat White,2,4.20,Card

In [6]:
(df["PaymentMethod"]).value_counts()

PaymentMethod
Card    9
UPI     6
Cash    5
Name: count, dtype: int64

In [7]:
df["UnitPrice"].max()

np.float64(28.0)

In [8]:
df["UnitPrice"].min()

np.float64(1.5)

In [9]:
print(pd.options.display.max_rows)

60

In [10]:
pd.options.display.max_rows = 61

Print the DataFrame without the to_string() method

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        20 non-null     int64
 1   Date           20 non-null     object
 2   Time           20 non-null     object
 3   Customer       20 non-null     object
 4   Category       20 non-null     object
 5   Product        20 non-null     object
 6   Quantity       20 non-null     int64
 7   UnitPrice      20 non-null     float64
 8   PaymentMethod  20 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 1.5+ KB
None