In [1]:
import pandas as pd 
import numpy as np

In [7]:
df = pd.read_csv("../CSV Files/Clean_Data.csv")

In [8]:
for x in df.index:
    if df.loc[x, "Duration"] > 100:
        df.loc[x, "Duration"] = 100

In [10]:
df.head(20)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

In [11]:
df.loc[62, "Duration"]

np.int64(100)

In [12]:
# One-Liner
df.loc[df["Duration"] > 100, "Duration"] = 100

In [15]:
# Delete rows where Duration is greater than 100

df = df[df["Duration"] < 100] # Only take those rows where duration is less than 100

In [22]:
practice_data = {
    "Student_ID": [101, 102, 103, 104, 101, 105, 106, 103, 107, 108],
    "Name": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
        "Alice",
        "Eva",
        "Frank",
        "Charlie",
        "Grace",
        "Henry",
    ],
    "Score": [85, 92, 78, 300, 85, None, 88, 78, 95, -10],
    "Attendance_Pct": [95, 80, 85, 90, 95, 60, 75, 85, 100, 82],
}

# Convert it to a DataFrame
df = pd.DataFrame(practice_data)
print(df_practice)

   Student_ID     Name  Score  Attendance_Pct
0         101    Alice   85.0              95
1         102      Bob   92.0              80
2         103  Charlie   78.0              85
3         104    David  300.0              90
4         101    Alice   85.0              95
5         105      Eva    NaN              60
6         106    Frank   88.0              75
7         103  Charlie   78.0              85
8         107    Grace   95.0             100
9         108    Henry  -10.0              82

In [23]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [24]:
df.drop_duplicates(inplace = True)

In [26]:
df.head()

   Student_ID     Name  Score  Attendance_Pct
0         101    Alice   85.0              95
1         102      Bob   92.0              80
2         103  Charlie   78.0              85
3         104    David  300.0              90
5         105      Eva    NaN              60

# Summary Checklist to follow:

1) Duplicates

2) Formats

3) NaNs

4) Impossible Values / Outliers